routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

Route::group(["middleware" => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath'], 'prefix' => LaravelLocalization::setLocale()], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Auth::routes();
    Route::get('/', function () {
        return view('welcome');
    });
    Route::group(["middleware" => "auth"], function () {
        Route::get('reportes', 'ReporteController@index')->name('reportes.index');
        Route::get('passport', 'PassportController@index')->middleware('role:admi')->name('passport.index');
        Route::resource("peliculas", "PeliculaController")->except(['store', 'update', 'destroy']);
        Route::resource("usuarios", "UserController")->except(['store', 'update', 'destroy', "create", "edit"])
            ->middleware('role:admi');
        Route::resource("generos", "GeneroController")->except(['create', 'edit', 'store', 'update']);
        Route::get('settings', 'UserController@settings')->name('settings');
        Route::post('change_password', 'UserController@change_password')->name('settings.store');
        Route::get('actores', function () {
            return view('panel.actores.index');
        })->name('actores.index');
    });
});
Route::group(["middleware" => "auth"], function () {
    Route::resource("peliculas", "PeliculaController")->only(['store', 'update', 'destroy']);
    Route::resource("usuarios", "UserController")->only(['store', 'update', 'destroy'])->middleware('role:admi');
    Route::post("generos/{id}/restore", "GeneroController@restore")->name("generos.restore");
    Route::post("generos/{id}/trash", "GeneroController@trash")->name("generos.trash");

    // Reportes
    Route::group(["prefix" => "reportes"], function () {
        Route::get("usuarios", "ReporteController@reporteUsuarios")->name('reportes.usuarios');
        Route::get("usuarios/excel", "ReporteController@reporteUsuariosExcel")->name('reportes.usuarios.excel');
        Route::get("peliculas/excel", "ReporteController@reportePeliculasExcel")->name('reportes.peliculas.excel');
        Route::get("generos/excel", "ReporteController@reporteGenerosExcel")->name('reportes.generos.excel');
    });
});

resources/views/panel/usuarios/create.blade.php
<!-- Modal -->
<div class="modal fade" id="modalCreate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Registrar Usuario</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {{Form::open(['url'=>'usuarios'])}}
        <div class="modal-body">
            <div class="form-group">
                <label for="name" class="col-form-label">Nick Name</label>
                <input required type="text" class="form-control" id="name" name="name">
            </div>
            <div class="form-group">
                <label for="email" class="col-form-label">Email</label>
                <input required type="email" class="form-control" id="email" name="email">
            </div>
            <div class="form-group">
                <label for="idRol" class="col-form-label">Rol</label>
                <select required class="form-control" id="idRol" name="idRol">
                    <option value="">-- Seleccionar --</option>
                    @foreach ($roles as $r)
                        <option value="{{$r->id}}">{{$r->display_name}}</option>
                    @endforeach
                </select>
            </div>
          </div>
          <div class="modal-footer">
            <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar">
            <input type="submit" class="btn btn-primary" value="Aceptar">
          </div>
          {{Form::Close()}}
      </div>
    </div>
  </div>

resources/views/panel/usuarios/edit.blade.php
<!-- Modal -->
<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Editar Usuario</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {!! Form::open(['route' => ['usuarios.update', ""],'method' => 'PATCH']) !!}
        <input type="hidden" value="{{Auth::id()}}" name="idUser">
        <div class="modal-body">
            <div class="form-group">
                <label for="name" class="col-form-label">Nick Name</label>
                <input readonly type="text" class="form-control" id="name">
            </div>
            <div class="form-group">
                <label for="email" class="col-form-label">Email</label>
                <input readonly type="email" class="form-control" id="email">
            </div>
            <div class="form-group">
                <label for="idRol" class="col-form-label">Rol</label>
                <select required class="form-control" id="idRol" name="idRol">
                    <option value="">-- Seleccionar --</option>
                    @foreach ($roles as $r)
                        <option value="{{$r->id}}">{{$r->display_name}}</option>
                    @endforeach
                </select>
            </div>
          </div>
          <div class="modal-footer">
            <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar">
            <input type="submit" class="btn btn-primary" value="Aceptar">
          </div>
          {{Form::Close()}}
      </div>
    </div>
  </div>

resources/views/panel/usuarios/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Usuarios  
                    <a title="Nuevo Usuario" data-toggle="modal" data-target="#modalCreate" 
                        href="#" class="btn btn-primary"><i class="fa fa-plus-circle" aria-hidden="true"></i></a>
                </div>
                <div class="card-body">
                    @include('includes.messages')
                    @include('panel.usuarios.create')
                    @include('panel.usuarios.edit')
                <div class="table-responsive">
                    {{$usuarios->links()}}
                    <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Fecha Creación</th>
                        <th scope="col">Última Actualización</th>
                        <th scope="col">Rol</th>
                        <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($usuarios as $u)
                            <tr>
                                <th scope="row">{{$u->name}}</th>
                                <td>{{$u->email}}</td>
                                <td>{{$u->created_at}}</td>
                                <td>{{$u->updated_at}}</td>
                                <td>
                                    @foreach ($u->roles as $r)
                                        {{$r->display_name}}
                                    @endforeach
                                </td>
                                <td>
                                    <a title="Ver" href="{{route('usuarios.show',$u->id)}}" class="btn btn-info btn-xs"><i class="fa fa-folder-open" aria-hidden="true"></i></a>
                                    <a title="Cambiar rol" data-toggle="modal" data-target="#modalEdit" 
                                    data-name="{{$u->name}}" data-email="{{$u->email}}" 
                                    data-rol="{{count($u->roles)== 0 ?: $u->roles[0]->id}}" 
                                    href="#" data-action="{{route('usuarios.update',$u->id)}}"
                                    class="btn btn-success btn-xs"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    </table>
                    {{$usuarios->links()}}
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@prepend('scripts')
<script type="text/javascript">
    $(document).ready(function () {
        $('#modalEdit').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var action = button.data('action');
            var name = button.data('name');
            var email = button.data('email');
            var idRol = button.data('rol');
            var modal = $(this);
            modal.find(".modal-content #name").val(name);
            modal.find(".modal-content #email").val(email);
            modal.find(".modal-content #idRol").val(idRol);
            modal.find(".modal-content form").attr('action', action);
        });
    });
</script>
@endprepend

resources/views/panel/usuarios/settings.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">@lang('messages.settings')</div>
                <div class="card-body">
                    @include('includes.messages')
                    <ul class="list-group">
                        <li class="list-group-item"><b>Nick Name:</b> {{$usuario->name}}</li>
                        <li class="list-group-item"><b>E-mail:</b> {{$usuario->email}}</li>
                        <li class="list-group-item"><b>Fecha Creación:</b> {{$usuario->created_at}}</li>
                        <li class="list-group-item"><b>Última Actualización:</b> {{$usuario->updated_at}}</li>
                        <li class="list-group-item"><b>Rol:</b> {{count($usuario->roles)== 0 ?: $usuario->roles[0]->display_name}}</li>
                    </ul>
                    <div id="accordion">
                            <div class="card">
                              <div class="card-header" id="headingOne">
                                <h5 class="mb-0">
                                  <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Cambiar contraseña
                                  </button>
                                </h5>
                              </div>
                          
                              <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                                <div class="card-body">
                                        {!! Form::open(['url' => \LaravelLocalization::getCurrentLocale().'/change_password']) !!}
                                            <div class="form-group row">
                                                <label for="password_now" class="col-sm-2 col-form-label">Contraseña actual</label>
                                                <div class="col-sm-10">
                                                    <input required type="password" class="form-control" id="password_now" name="password_now" minlength="8" maxlength="25">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label for="password" class="col-sm-2 col-form-label">Nueva contraseña</label>
                                                <div class="col-sm-10">
                                                    <input required type="password" class="form-control" id="password" name="password" minlength="8" maxlength="25">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label for="password_confirmed" class="col-sm-2 col-form-label">Confirmar contraseña</label>
                                                    <div class="col-sm-10">
                                                    <input required type="password" class="form-control" id="password_confirmed" name="password_confirmation" minlength="8" maxlength="25">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-sm-10">
                                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                                </div>
                                            </div>
                                        {!! Form::close() !!}
                                </div>
                              </div>
                            </div>
                          </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/panel/usuarios/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Información del usuario <a class="btn btn-primary" href="{{url('usuarios')}}" title="Regresar al listado" role="button">
                            <i class="fa fa-reply" aria-hidden="true"></i>
                    </a></div>
                    <div class="card-body">
                        <ul class="list-group">
                            <li class="list-group-item"><b>Nick Name:</b> {{$usuario->name}}</li>
                            <li class="list-group-item"><b>E-mail:</b> {{$usuario->email}}</li>
                            <li class="list-group-item"><b>Fecha Creación:</b> {{$usuario->created_at}}</li>
                            <li class="list-group-item"><b>Última Actualización:</b> {{$usuario->updated_at}}</li>
                        </ul>
                        <h4>Roles</h4>
                        @if (count($usuario->roles) > 0)
                            <ul class="list-group">
                                @foreach ($usuario->roles as $rol)
                                    <li class="list-group-item">{{$rol->display_name}}</li>
                                @endforeach
                            </ul>
                        @else
                            <div class="alert alert-info alert-dismissible fade show" role="alert">
                                <strong>El usuario no tiene asignado un rol</strong>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection