routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

Route::group(["middleware" => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath'], 'prefix' => LaravelLocalization::setLocale()], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Auth::routes();
    Route::get('/', function () {
        return view('welcome');
    });
    Route::group(["middleware" => "auth"], function () {
        Route::get('reportes', 'ReporteController@index')->name('reportes.index');
        Route::get('passport', 'PassportController@index')->middleware('role:admi')->name('passport.index');
        Route::resource("peliculas", "PeliculaController")->except(['store', 'update', 'destroy']);
        Route::resource("usuarios", "UserController")->except(['store', 'update', 'destroy', "create", "edit"])
            ->middleware('role:admi');
        Route::resource("generos", "GeneroController")->except(['create', 'edit', 'store', 'update']);
        Route::get('settings', 'UserController@settings')->name('settings');
        Route::post('change_password', 'UserController@change_password')->name('settings.store');
        Route::get('actores', function () {
            return view('panel.actores.index');
        })->name('actores.index');
    });
});
Route::group(["middleware" => "auth"], function () {
    Route::resource("peliculas", "PeliculaController")->only(['store', 'update', 'destroy']);
    Route::resource("usuarios", "UserController")->only(['store', 'update', 'destroy'])->middleware('role:admi');
    Route::post("generos/{id}/restore", "GeneroController@restore")->name("generos.restore");
    Route::post("generos/{id}/trash", "GeneroController@trash")->name("generos.trash");

    // Reportes
    Route::group(["prefix" => "reportes"], function () {
        Route::get("usuarios", "ReporteController@reporteUsuarios")->name('reportes.usuarios');
        Route::get("usuarios/excel", "ReporteController@reporteUsuariosExcel")->name('reportes.usuarios.excel');
        Route::get("peliculas/excel", "ReporteController@reportePeliculasExcel")->name('reportes.peliculas.excel');
        Route::get("generos/excel", "ReporteController@reporteGenerosExcel")->name('reportes.generos.excel');
    });
});

app/Genero.php
<?php

namespace App;

use App\Notifications\GeneroNotification;
use Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OneSignal;

class Genero extends Model
{
    use SoftDeletes;

    protected $primaryKey = "idGenero";
    protected $table = "generos";
    public $timestamps = true;

    protected $fillable = ['nombre'];
    protected $hidden = ['pivot'];

    protected $dates = ['deleted_at'];

    public function peliculas()
    {
        return $this->belongsToMany('\App\Pelicula', 'peliculas_generos', 'idGenero', 'idPelicula');
    }

    protected static function boot()
    {
        parent::boot();

        static::deleted(function ($genero) {
            $route = route("generos.show", $genero->idGenero);
            OneSignal::sendNotificationToAll("Se envió a papelera el género " . $genero->nombre . " a las " . $genero->deleted_at, $route);
            $user = Auth::user();
            $user->notify(new GeneroNotification($genero));
        });
        static::restoring(function ($genero) {
            info("restoring");
            $user = Auth::user();
            $user->notify(new GeneroNotification($genero, true));
        });

    }
}

app/Http/Controllers/GeneroController.php
<?php

namespace App\Http\Controllers;

use App\Genero;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Lang;

class GeneroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = Genero::query();
        $query = $query->withCount('peliculas')->orderBy('nombre');
        if ($request->display == "all") {
            $query->withTrashed();
        } else if ($request->display == "trash") {
            $query->onlyTrashed();
        }
        $generos = $query->paginate(10);
        return view('panel.generos.index', compact('generos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return Genero::withTrashed()->where('idGenero', $id)
            ->firstOrFail()->toJson();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            Genero::withTrashed()->where('idGenero', $id)->forceDelete();
            return redirect('generos')->with('success', 'Género eliminado permanentemente');
        } catch (Exception | QueryException $e) {
            return back()->withErrors(['exception' => $e->getMessage()]);
        }
    }

    public function restore($id)
    {
        try {
            Genero::withTrashed()->where('idGenero', $id)->restore(); // devuelve el # de generos restaurados
            return redirect('generos')->with('success', 'Género restaurado');
        } catch (Exception $e) {
            return back()->withErrors(['exception' => $e->getMessage()]);
        }
    }

    public function trash($id)
    {
        try {
            Genero::destroy($id);
            $gen = Genero::withTrashed()->where('idGenero', $id)->first();
            return redirect('generos')->with('success', Lang::get("messages.gender_trash", ['name' => $gen->nombre]));
        } catch (Exception $e) {
            return back()->withErrors(['exception' => $e->getMessage()]);
        }
    }
}

resources/views/panel/generos/delete.blade.php
<!-- Modal -->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Eliminar Género Permanentemente</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {{Form::open(['route'=>['generos.destroy',""],'method'=>'delete'])}}
        <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <h6 id="txtDelete">¿Está seguro de eliminar permanentemente el género?</h6>
                    </div>
                </div>
          </div>
          <div class="modal-footer">
            <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar">
            <input type="submit" class="btn btn-primary" value="Aceptar">
          </div>
          {{Form::Close()}}
      </div>
    </div>
  </div>

resources/views/panel/generos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Géneros  <a class="btn btn-primary" href="{{url('generos/create')}}" title="Nuevo género" role="button">
                    <i class="fa fa-plus-circle" aria-hidden="true"></i>
                </a></div>
                <div class="card-body">
                    @include('includes.messages')
                    @include('panel.generos.delete')
                    @include('panel.generos.trash')
                    @include('panel.generos.restore')
                <a class="btn btn-link {{strpos(Request::fullUrl(), 'generos?display=all') ? 'disabled' : ''}}" href="{{URL::action('GeneroController@index',['display'=>'all'])}}">@lang("messages.all")</a> | 
                <a class="btn btn-link" href="{{url('generos')}}">@lang("messages.actives")</a> | 
                <a class="btn btn-link {{strpos(Request::fullUrl(), 'generos?display=trash') ? 'disabled' : ''}}" href="{{URL::action('GeneroController@index',['display'=>'trash'])}}">@lang("messages.trash")</a>
                <div class="table-responsive">
                    {{$generos->appends(Request::capture()->except('page'))->links()}}
                    <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Películas</th>
                        <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($generos as $gen)
                            <tr>
                                <th scope="row">{{$gen->nombre}}</th>
                                <td>
                                    <span class="badge badge-pill badge-{{$gen->peliculas_count == 0 ? 'danger' : 'info' }}">{{$gen->peliculas_count}}</span>
                                </td>
                                <td>
                                    @if ($gen->trashed())
                                        <a title="Restaurar" data-toggle="modal" data-target="#modalRestore" 
                                        data-name="{{$gen->nombre}}" href="#"
                                        data-action="{{route('generos.restore',$gen->idGenero)}}"
                                        class="btn btn-success btn-xs"><i class="fa fa-archive" aria-hidden="true"></i></a>
                                        <a title="Borrar permanentemente" data-toggle="modal" data-target="#modalDelete" 
                                        data-name="{{$gen->nombre}}" href="#"
                                        data-action="{{route('generos.destroy',$gen->idGenero)}}"
                                        class="btn btn-warning btn-xs"><i class="fa fa-thumbs-down" aria-hidden="true"></i></a>
                                    @else
                                        <a title="Ver" href="{{route('generos.show',$gen->idGenero)}}" class="btn btn-info btn-xs"><i class="fa fa-folder-open" aria-hidden="true"></i></a>
                                        <a title="Editar" href="#" class="btn btn-primary btn-xs"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                        <a title="Enviar a papelera" data-toggle="modal" data-target="#modalTrash" 
                                        data-name="{{$gen->nombre}}" href="#"
                                        data-action="{{route('generos.trash',$gen->idGenero)}}"
                                        class="btn btn-danger btn-xs"><i class="fa fa-trash" aria-hidden="true"></i></a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        @if (count($generos)==0)
                            <tr>
                                <td style="text-align:center" colspan="3">No existen géneros registrados</td>
                            </tr>
                        @endif
                    </tfoot>
                    </table>
                    {{$generos->appends(Request::capture()->except('page'))->links()}}
                </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@prepend('scripts')
<script type="text/javascript">
    $(document).ready(function () {
        $('#modalTrash').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var action = button.data('action');
            var name = button.data('name');
            var modal = $(this);
            modal.find(".modal-content #txtTrash").html("¿Está seguro de eliminar el género <b>" + name + "</b>?");
            modal.find(".modal-content form").attr('action', action);
        });
        $('#modalDelete').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var action = button.data('action');
            var name = button.data('name');
            var modal = $(this);
            modal.find(".modal-content #txtDelete").html("¿Está seguro de eliminar permanentemente el género <b>" + name + "</b>?");
            modal.find(".modal-content form").attr('action', action);
        });
        $('#modalRestore').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var action = button.data('action');
            var name = button.data('name');
            var modal = $(this);
            modal.find(".modal-content #txtRestore").html("¿Está seguro de restaurar el género <b>" + name + "</b>?");
            modal.find(".modal-content form").attr('action', action);
        });
    });
</script>
@endprepend

resources/views/panel/generos/restore.blade.php
<!-- Modal -->
<div class="modal fade" id="modalRestore" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Restaurar Género</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {{Form::open(['route'=>['generos.restore',""]])}}
        <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <h6 id="txtRestore">¿Está seguro de restaurar el género?</h6>
                    </div>
                </div>
          </div>
          <div class="modal-footer">
            <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar">
            <input type="submit" class="btn btn-primary" value="Aceptar">
          </div>
          {{Form::Close()}}
      </div>
    </div>
  </div>

resources/views/panel/generos/trash.blade.php
<!-- Modal -->
<div class="modal fade" id="modalTrash" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Eliminar Género</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {{Form::open(['route'=>['generos.trash',""]])}}
        <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <h6 id="txtTrash">¿Está seguro de eliminar el género?</h6>
                        <h6>El registro se enviará a la papelera.</h6>
                    </div>
                </div>
          </div>
          <div class="modal-footer">
            <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar">
            <input type="submit" class="btn btn-primary" value="Aceptar">
          </div>
          {{Form::Close()}}
      </div>
    </div>
  </div>