routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

Route::group(["middleware" => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath'], 'prefix' => LaravelLocalization::setLocale()], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Auth::routes();
    Route::get('/', function () {
        return view('welcome');
    });
    Route::group(["middleware" => "auth"], function () {
        Route::get('reportes', 'ReporteController@index')->name('reportes.index');
        Route::get('passport', 'PassportController@index')->middleware('role:admi')->name('passport.index');
        Route::resource("peliculas", "PeliculaController")->except(['store', 'update', 'destroy']);
        Route::resource("usuarios", "UserController")->except(['store', 'update', 'destroy', "create", "edit"])
            ->middleware('role:admi');
        Route::resource("generos", "GeneroController")->except(['create', 'edit', 'store', 'update']);
        Route::get('settings', 'UserController@settings')->name('settings');
        Route::post('change_password', 'UserController@change_password')->name('settings.store');
        Route::get('actores', function () {
            return view('panel.actores.index');
        })->name('actores.index');
    });
});
Route::group(["middleware" => "auth"], function () {
    Route::resource("peliculas", "PeliculaController")->only(['store', 'update', 'destroy']);
    Route::resource("usuarios", "UserController")->only(['store', 'update', 'destroy'])->middleware('role:admi');
    Route::post("generos/{id}/restore", "GeneroController@restore")->name("generos.restore");
    Route::post("generos/{id}/trash", "GeneroController@trash")->name("generos.trash");

    // Reportes
    Route::group(["prefix" => "reportes"], function () {
        Route::get("usuarios", "ReporteController@reporteUsuarios")->name('reportes.usuarios');
        Route::get("usuarios/excel", "ReporteController@reporteUsuariosExcel")->name('reportes.usuarios.excel');
        Route::get("peliculas/excel", "ReporteController@reportePeliculasExcel")->name('reportes.peliculas.excel');
        Route::get("generos/excel", "ReporteController@reporteGenerosExcel")->name('reportes.generos.excel');
    });
});

app/Pelicula.php
<?php

namespace App;

use Auth;
use DB;
use Illuminate\Database\Eloquent\Model;
use Input;
use Storage;

class Pelicula extends Model
{
    protected $primaryKey = "idPelicula";
    protected $table = "peliculas";
    public $timestamps = true;

    public $fillable = ['titulo', 'duracion', 'anio', 'imagen', 'idUser'];

    protected $hidden = ['pivot'];

    public function usuario()
    {
        return $this->belongsTo('\App\User', 'idUser')
            ->withDefault(function ($user) {
                $user->name = 'Guest Author';
            });
    }

    public function generos()
    {
        return $this->belongsToMany('\App\Genero', 'peliculas_generos', 'idPelicula', 'idGenero');
    }

    public function actores()
    {
        return $this->belongsToMany('\App\Actor', 'peliculas_actores', 'idPelicula', 'idActor');
    }

    public function scopeCortas($query)
    {
        return $query->where('duracion', '<', '120');
    }

    public function scopeActuales($query)
    {
        return $query->where('anio', date('Y'));
    }

    public function scopeAgrupar($query)
    {
        return $query->select('anio', 'duracion', DB::raw('count(*) as registros'))
            ->groupBy('anio', 'duracion');
    }

    public static function findGenero($array, $idGenero)
    {
        foreach ($array as $item) {
            foreach ($item as $value) {
                if ($value == $idGenero) {
                    return true;
                }
            }
        }
        return false;
    }

    protected static function boot()
    {
        parent::boot();

        static::deleting(function ($pelicula) { // before delete() method call this
            $pelicula->generos()->detach();
            if ($pelicula->imagen != null) {
                Storage::delete($pelicula->imagen);
            }
        });

        static::creating(function ($pelicula) {
            $pelicula->idUser = Auth::id();
            if (Input::hasFile('imagen') && $pelicula->imagen != null) {
                $image = Input::file('imagen');
                $pelicula->imagen = $image->store('public/peliculas');
            }
        });

    }
}

app/Http/Controllers/PeliculaController.php
<?php

namespace App\Http\Controllers;

use App\Genero;
use App\Http\Requests\PeliculaRequest;
use App\Pelicula;
use Illuminate\Http\Request;

class PeliculaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $peliculas = Pelicula::withCount('generos')->with("usuario:id,name")
            ->orderByDesc('anio')->orderBy('titulo')->paginate(10);
        return view('panel.peliculas.index', compact('peliculas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $generos = Genero::orderBy('nombre')->get(['idGenero', 'nombre']);
        return view("panel.peliculas.create", compact('generos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\PeliculaRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PeliculaRequest $request)
    {
        try {
            $pelicula = Pelicula::create($request->except(['idGenero']));
            $pelicula->generos()->sync($request->idGenero);
            return redirect('peliculas')->with('success', 'Película registrada');
        } catch (Exception $e) {
            return back()->withErrors(['exception' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pelicula = Pelicula::with(['generos' => function ($query) {
            $query->select('nombre');
        }])->findOrFail($id);
        return view("panel.peliculas.show", compact('pelicula'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pelicula = Pelicula::with(['generos' => function ($query) {
            $query->select('generos.idGenero');
        }])->findOrFail($id);
        $generos = Genero::orderBy('nombre')->get(['idGenero', 'nombre']);
        $gens = collect($pelicula->generos)->sortBy('idGenero')->toArray();
        return view("panel.peliculas.edit", compact('pelicula', 'generos', 'gens'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\PeliculaRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PeliculaRequest $request, $id)
    {
        try {
            $this->authorize('update', Pelicula::findOrFail($id));
            $pelicula = Pelicula::updateOrCreate(['idPelicula' => $id], $request->except('idGenero'));
            $pelicula->generos()->sync($request->idGenero);
            return redirect('peliculas')->with('success', 'Pelicula actualizada');
        } catch (Exception $e) {
            return back()->withErrors(['exception' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            Pelicula::destroy($id);
            return redirect('peliculas')->with('success', 'Película eliminada');
        } catch (Exception $e) {
            return back()->withErrors(['exception' => $e->getMessage()]);
        }
    }

    public function findMovie($idPelicula)
    {
        $pelicula = Pelicula::where('idPelicula', $idPelicula)
            ->firstOrFail(['idPelicula', 'titulo', 'duracion', 'anio', 'idUser']);
        return $pelicula->toJson();
    }
}

resources/views/panel/peliculas/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Nueva Película <a class="btn btn-primary" href="{{url('peliculas')}}" title="Regresar al listado" role="button">
                            <i class="fa fa-reply" aria-hidden="true"></i>
                    </a></div>
                    <div class="card-body">
                        @include('includes.messages')
                        {!! Form::open(['url' => 'peliculas','files'=>'true']) !!}
                            <div class="form-group row">
                                <label for="titulo" class="col-sm-2 col-form-label">Título</label>
                                <div class="col-sm-10">
                                    <input required type="text" class="form-control" id="titulo" name="titulo" value="{{old('titulo')}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="duracion" class="col-sm-2 col-form-label">Duración</label>
                                <div class="col-sm-4">
                                    <input required type="number" min="50" max="500" class="form-control" id="duracion" name="duracion" value="{{old('duracion')}}">
                                </div>
                                <label for="anio" class="col-sm-2 col-form-label">Año</label>
                                <div class="col-sm-4">
                                    <input required type="number" min="1950" max="{{date('Y')}}" class="form-control" id="anio" name="anio" value="{{old('anio')}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="imagen" class="col-sm-2 col-form-label">Imagen</label>
                                <div class="col-sm-10">
                                    <input type="file" class="form-control" id="imagen" name="imagen">
                                </div>
                            </div>
                            <div class="form-group">
                                    <label for="generos">Géneros</label>
                                    <div style="height:300px;overflow-y: scroll;">
                                        @foreach ($generos as $gen)
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" value="{{$gen->idGenero}}" name="idGenero[]">
                                                <label class="form-check-label">
                                                      {{$gen->nombre}}
                                                  </label>
                                                </div>
                                        @endforeach
                                    </div>
                            </div>
                            <div class="form-group row">
                                    <div class="col-sm-10">
                                      <button type="submit" class="btn btn-primary">Guardar</button>
                                    </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/panel/peliculas/delete.blade.php
<!-- Modal -->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Eliminar Película</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {{Form::open(['route'=>['peliculas.destroy',""],'method'=>'delete'])}}
            <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h6 id="txtEliminar">¿Está seguro de eliminar la película?</h6>
                        </div>
                    </div>
              </div>
              <div class="modal-footer">
                <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar">
                <input type="submit" class="btn btn-primary" value="Aceptar">
              </div>
              {{Form::Close()}}
          </div>
        </div>
      </div>
    

resources/views/panel/peliculas/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Editar Película <a class="btn btn-primary" href="{{url('peliculas')}}" title="Regresar al listado" role="button">
                            <i class="fa fa-reply" aria-hidden="true"></i>
                    </a></div>
                    <div class="card-body">
                        @include('includes.messages')
                        {!! Form::open(['route' => ['peliculas.update', $pelicula->idPelicula],'method' => 'PATCH']) !!}
                            <div class="form-group row">
                                <label for="titulo" class="col-sm-2 col-form-label">Título</label>
                                <div class="col-sm-10">
                                    <input required type="text" class="form-control" id="titulo" name="titulo" value="{{$pelicula->titulo}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="duracion" class="col-sm-2 col-form-label">Duración</label>
                                <div class="col-sm-4">
                                    <input required type="number" min="50" max="500" class="form-control" id="duracion" name="duracion" value="{{$pelicula->duracion}}">
                                </div>
                                <label for="anio" class="col-sm-2 col-form-label">Año</label>
                                <div class="col-sm-4">
                                    <input required type="number" min="1950" max="{{date('Y')}}" class="form-control" id="anio" name="anio" value="{{$pelicula->anio}}">
                                </div>
                            </div>
                            <div class="form-group">
                                    <label for="generos">Géneros <span class="badge badge-info">{{count($gens)}}</span></label>
                                    <div style="height:300px;overflow-y: scroll;">
                                      @foreach ($generos as $gen)
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" {{\App\Pelicula::findGenero($gens,$gen->idGenero) ? 'checked' : ''}} value="{{$gen->idGenero}}" name="idGenero[]">
                                            <label class="form-check-label">
                                                {{$gen->nombre}}
                                            </label>
                                          </div>
                                      @endforeach
                                    </div>
                            </div>
                            <div class="form-group row">
                                    <div class="col-sm-10">
                                      <button type="submit" class="btn btn-primary">Guardar</button>
                                    </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/panel/peliculas/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Películas  <a class="btn btn-primary" href="{{url('peliculas/create')}}" title="Nueva película" role="button">
                    <i class="fa fa-plus-circle" aria-hidden="true"></i>
                </a></div>
                <div class="card-body">
                    @include('includes.messages')
                    @include('panel.peliculas.delete')
                <div class="table-responsive">
                    {{$peliculas->links()}}
                    <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">Título</th>
                        <th scope="col">Año</th>
                        <th scope="col">Duración</th>
                        <th scope="col">Géneros</th>
                        <th scope="col">Autor</th>
                        <th scope="col">Imagen</th>
                        <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($peliculas as $pel)
                            <tr>
                                <th scope="row">{{$pel->titulo}}</th>
                                <td>{{$pel->anio}}</td>
                                <td>{{$pel->duracion}}</td>
                                <td>
                                    <span class="badge badge-pill badge-{{$pel->generos_count == 0 ? 'danger' : 'info' }}">{{$pel->generos_count}}</span>
                                </td>
                                <td>{{$pel->usuario->name}}</td>
                                <td>
                                    @if($pel->imagen == null)
                                        -
                                    @else
                                        <img src="{{\Storage::url($pel->imagen)}}" style="max-width:75px;">
                                    @endif
                                </td>
                                <td>
                                    <a title="Ver" href="{{route('peliculas.show',$pel->idPelicula)}}" class="btn btn-info btn-xs"><i class="fa fa-folder-open" aria-hidden="true"></i></a>
                                    @can('update', $pel)
                                        <a title="Editar" href="{{route('peliculas.edit',$pel->idPelicula)}}" class="btn btn-primary btn-xs"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                        <a title="Eliminar" data-toggle="modal" data-target="#modalDelete" 
                                    data-name="{{$pel->titulo}}" href="#"
                                    data-action="{{route('peliculas.destroy',$pel->idPelicula)}}"
                                    class="btn btn-danger btn-xs"><i class="fa fa-trash" aria-hidden="true"></i></a>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    </table>
                    {{$peliculas->links()}}
                </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@prepend('scripts')
<script type="text/javascript">
    $(document).ready(function () {
        $('#modalDelete').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var action = button.data('action');
            var name = button.data('name');
            var modal = $(this);
            modal.find(".modal-content #txtEliminar").html("¿Está seguro de eliminar la película <b>" + name + "</b>?");
            modal.find(".modal-content form").attr('action', action);
        });
    });
</script>
@endprepend

resources/views/panel/peliculas/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Información de la película <a class="btn btn-primary" href="{{url('peliculas')}}" title="Regresar al listado" role="button">
                            <i class="fa fa-reply" aria-hidden="true"></i>
                    </a></div>
                    <div class="card-body">
                        <ul class="list-group">
                            <li class="list-group-item"><b>Título:</b> {{$pelicula->titulo}}</li>
                            <li class="list-group-item"><b>Duración:</b> {{$pelicula->duracion}} minutos</li>
                            <li class="list-group-item"><b>Año:</b> {{$pelicula->anio}}</li>
                            <li class="list-group-item"><b>Imagen:</b> 
                                @if($pelicula->imagen == null)
                                    -
                                @else
                                    <img src="{{\Storage::url($pelicula->imagen)}}" style="max-height:300px;">
                                @endif
                            </li>
                        </ul>
                        <h4>Géneros</h4>
                        @if (count($pelicula->generos) > 0)
                            <ul class="list-group">
                                @foreach ($pelicula->generos as $gen)
                                    <li class="list-group-item">{{$gen->nombre}}</li>
                                @endforeach
                            </ul>
                        @else
                            <div class="alert alert-info alert-dismissible fade show" role="alert">
                                <strong>La película no tiene géneros registrados</strong>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection